### ISSUE TITLE
Can not switch cameras

### ISSUE THREAD

**Issue by phuhl** [BlackBoxVision/react-qr-reader#10]
On my device, the camera is the user facing camera and all input on the `facingMode` prop does not make a difference. From the code it also looks like, different than the docu in the README, the default is user facing:

https://github.com/BlackBoxVision/react-qr-reader/blob/450f49e6d60b0eccf7548086721fa7c5cf26f3a0/src/QrReader/index.tsx#L39-L40

**Comment by JonatanSalas** [comment]
Would you mind trying v4? 

You can install it by doing `npm i @blackbox-vision/react-qr-reader@4.0.0`. 

We've made a bigger change in the way of customizing the access to the camera, we now let you pass directly the `MediaTrackConstraints` so you can configure the best options for your use case.

**Comment by phuhl** [comment]
Sure, how would I configure the camera facing direction with v4?

**Comment by JonatanSalas** [comment]
Passing a prop called `constraints`, if you want to use the rear or back camera you can pass the prop like this `constraints={{ facingMode: 'environment' }}`

**Comment by phuhl** [comment]
Thanks, that worked!

**Comment by phuhl** [comment]
Could you publish with the new peerDependencies for v4, too? That would solve all my problems for the day :)

**Comment by JonatanSalas** [comment]
I'll check it out, I think I've already updated before making v4 release. Cool that worked! You're welcome, I'm closing this issue. We'll improve documentation on the usage of the library soon by launching a docs website. If you liked you can help us recommending it, and giving us a star!

**Comment by JonatanSalas** [comment]
I've checked the peerDependencies by running `npm view @blackbox-vision/react-qr-reader peerDependencies` and it prints out the following output:

```bash
{
  '@zxing/browser': '0.0.7',
  '@zxing/library': '^0.18.3',
  react: '^16.8.0 || ^17.0.0',
  'react-dom': '^16.8.0 || ^17.0.0'
}
```

Maybe you've something cached.
