### ISSUE TITLE
v4: className not working

### ISSUE THREAD

**Issue by phuhl** [BlackBoxVision/react-qr-reader#12]
Sorry, that I'am opening yet another issue, but it seems that v4 broke the className prop on the component. The classes appear to not be placed on the container anymore

**Comment by JonatanSalas** [comment]
Yes, you're right, fixing it ASAP!

**Comment by JonatanSalas** [comment]
@phuhl fixed, just update to `@blackbox-vision/react-qr-reader@4.0.1` and let me know!

**Comment by phuhl** [comment]
Thanks for the fast fix, worked!

**Comment by JonatanSalas** [comment]
You're welcome!
