### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by polymorpher** [BlackBoxVision/react-qr-reader#13]
![image](https://user-images.githubusercontent.com/913871/123600257-57f53800-d7ab-11eb-990e-0edcbb078965.png)

**Comment by JonatanSalas** [comment]
It's fixed, check it out here https://blackboxvision.github.io/react-qr-reader/?path=/docs/browser-qr-reader--scan-code and let me know if it does the work for you, we've an old version pushed.

**Comment by polymorpher** [comment]
Nice, demo works perfectly. While the demo wasn't working I just customized and implemented JodusNodus/react-qr-reader for my project, but I will switch over later.

**Comment by JonatanSalas** [comment]
Great! We'll be improving the docs. Thank you for reporting the demo wasn't working!
