### ISSUE TITLE
QrReader width doesn't change

### ISSUE THREAD

**Issue by sarahrbs** [BlackBoxVision/react-qr-reader#14]
May I know how I can change the width of the QrReader container.
style={{ width: '100%' }} - Changing width here has not effect.

**Comment by JonatanSalas** [comment]
Hi, currently we don't have a really good support to override styles. I've added a proposal in the following issue https://github.com/BlackBoxVision/react-qr-reader/issues/15 to keep the track of the development.

**Comment by JonatanSalas** [comment]
@sarahrbs as a workaround we've added support for `containerStyle`, `videoContainerStyle` and `videoStyle` so you can override the styling. 

You can checkout the docs [here](https://github.com/BlackBoxVision/react-qr-reader#component-api). For now this is a faster workaround until we resolve and implement a better CSS API. 

To test this newer props you can install our library by doing:

```bash
npm i @blackbox-vision/react-qr-reader@4.1.0
```
