### ISSUE TITLE
There's any way to have an image of the canvas? like base64 or something?

### ISSUE THREAD

**Issue by YisusMB** [BlackBoxVision/react-qr-reader#17]
Im thinking about have a live preview of a scaned code when this is readed

Actually the bitmap donst like to result in a image... so i tried a little but doesnt result...

**Comment by JonatanSalas** [comment]
Hi @YisusMB, would you mind to explain a little in which use case would you need to have a preview of the scanned code? I'd like to understand this, because I want this library to keep as lean as possible.

**Comment by YisusMB** [comment]
Hi! I think  a lot about how can i capture the specific frame when a code are readed, at this point i solved this like this:
```js
  const captureVideo = (video: any) => {
    try {
      var canvas = document.createElement("canvas");
      canvas.width = video.videoWidth;
      canvas.height = video.videoHeight;
      var canvasContext = canvas.getContext("2d");
      canvasContext.drawImage(video, 0, 0);
      return canvas.toDataURL("image/png");
    } catch (e) {
      console.log(e);
    }
  };
```

```js
const onScan = async (result: any, errorScanner: any) => {
  const getFrame = captureVideo(document.getElementById("qrreader"));
}
```

```js
  <QrReader
    videoId={"qrreader"}
    onResult={onScan}
    videoContainerStyle={{ width: "100%", height: "100%" }}
    constraints={{ facingMode: "environment" }}
   />
```

and ill close this issue with this workaround
