### ISSUE TITLE
Setting faceMode to environment doesn't change anything

### ISSUE THREAD

**Issue by shivangag** [BlackBoxVision/react-qr-reader#28]
I set the constraint to {facingMode: "environment"}, then tested it on a smartphone, but the package is still accessing the user facing camera. Using the original react-qr-reader package and setting facingMode prop to environment works correctly on the same smartphone.

**Comment by buffcode** [comment]
@shivangag I am doing the same and on a iPhone 10 / iOS 14.7.1 with both Safari and Chrome everything works as expected.
What is your environment?

Maybe try to use `exact` in the constrain ([MDN doc](https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints/facingMode)).

Code in my project:
```js
<QrReader
  onResult={(result, error) => {
    if (error || !result) {
      return;
    }

    onData(result.getText());
  }}
  constraints={{
    aspectRatio: 1,
    facingMode: 'environment',
  }}
  videoStyle={{ height: 'auto' }}
  containerStyle={{ width: '100%' }}
/>
```

**Comment by JonatanSalas** [comment]
@shivangag which version of the library are you using? is the issue fixed for you?

**Comment by shivangag** [comment]
@buffcode @JonatanSalas it is working now. Thanks!
