### ISSUE TITLE
Update to react 17

### ISSUE THREAD

**Issue by phuhl** [BlackBoxVision/react-qr-reader#8]
Hi, thanks for maintaining this repo. Is there a plan for updating to react 17?

**Comment by JonatanSalas** [comment]
I would like to understand, React 17 only introduces the new JSX transform which allows avoid importing React at the top level of every component we declare, are you having any issue with a React 17 app? Would like to have more information.

**Comment by phuhl** [comment]
This other issue on another fork says, it "should be painless": kybarg/react-qr-scanner#42

The braking chases between 16 and 17 are quite small, indeed. But thorough testing is advised, I guess.

**Comment by JonatanSalas** [comment]
Yeah, maybe we should test it, but I guess that there are no issues with React 17. Maybe we should have to put more eyes on React 18 which will introduce tons of breaking changes.

**Comment by phuhl** [comment]
Do you have a timeline until when this could be done? Currently I am trying to install this package with --legacy-peer-deps in my react 17 project. Not yet sure if it works. A version that could be installed properly would be very much appreciated! :)

**Comment by JonatanSalas** [comment]
It's not a bigger change really, it's changing the package.json peer deps, if you want we accept a PR supporting it.

**Comment by phuhl** [comment]
I can change the package.json, but I don't know by which means you test this package. I am not familiar with storybook. What is your testing flow?

**Comment by JonatanSalas** [comment]
Closing this issue since we've already launched a fix for it in v3 and v4 versions.
